### PR TITLE
Add CI workflow to run sesterl tests on Github Actions

### PR DESCRIPTION
**Pull request by michallepicki**

### CODE REVIEW

**Comment by gfngfn** [comment]
Thank you so much for setting up the CI workflow! I will merge this PR first and see the result of the workflow.

**Comment by michallepicki** [comment]
Looks to be working

These short bash snippets are what I've personally been using for installing Erlang and Rebar, but alternatively the https://github.com/erlef/setup-beam/ action can be used

**Comment by gfngfn** [comment]
Seems working fine!

**Comment by michallepicki** [comment]
I think one issue is that those sesterl artifacts attached to GitHub Actions builds expire (depending on repository settings, by default after 90 days I think) so when this becomes a problem it would be good to start attaching the build artifacts to releases on sesterl repo

**Pull request merged**
